import Head from "next/head";
import Image from "next/image";
import axios from "axios";
import { useEffect, useState } from "react";
import { BsSearch } from "react-icons/bs";
import Weather from "../components/Weather";
import Spinner from "../components/Spinner";
import Error from "../components/Error";

export default function Home() {
	const [city, setCity] = useState("Boston");
	const [weather, setWeather] = useState({});
	const [loading, setLoading] = useState(false);
	const [error, setError] = useState(false);

	const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

	useEffect(() => {
		fetchWeather();
	}, []);

	const fetchWeather = async () => {
		setLoading(true);
		setError(false);
		setWeather({});
		axios
			.get(url)
			.then((response) => {
				setWeather(response.data);
				console.log(response.data);
			})
			.catch(function (error) {
				setError(true);
				setLoading(false);
			});
		setCity("");
		setLoading(false);
	};

	const handleFormSubmit = (e) => {
		e.preventDefault();
		fetchWeather();
	};

	return (
		<div className="h-screen">
			<Head>
				<title>Weather - Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="absolute top-0 left-0 right-0 bottom-0 bg-indigo-900/[80%]">
				<div className="relative flex justify-between items-center max-w-[700px] w-full m-auto pt-4 px-4 text-white z-30">
					<form
						onSubmit={handleFormSubmit}
						className="flex justify-between items-center w-full m-auto bg-transparent border-none text-white"
					>
						<input
							onChange={(e) => setCity(e.target.value)}
							className="bg-transparent border-2 border-white p-5 h-20 rounded-tl-2xl rounded-bl-2xl text-white focus:outline-none text-2xl w-full placeholder-white transition ease-in duration-150 hover:shadow-2xl focus:border-emerald-200/[60%]"
							type="text"
							placeholder="Search city"
						/>

						<button
							className="border-2 border-white h-20 p-5 rounded-tr-2xl rounded-br-2xl bg-emerald-200/[60%] hover:bg-emerald-400/[60%] active:shadow-inner"
							type="submit"
						>
							<BsSearch className="h-full" size={25} />
						</button>
					</form>
				</div>
			</div>

			{error && <Error />}
			{loading && <Spinner />}
			{!loading && weather.main && <Weather data={weather} />}
		</div>
	);
}
